name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: تحميل ملفات المشروع
        uses: actions/checkout@v4

      - name: إعداد Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: إعداد Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.10.2"

      - name: بناء التطبيق
        run: gradle assembleDebug

      - name: رفع ملف APK
        uses: actions/upload-artifact@v4
        with:
          name: Maqadi-APK
          path: app/build/outputs/apk/debug/app-debug.apk
